### ISSUE TITLE
Работа библиотеки на локальном сервере

### ISSUE THREAD

**Issue by aspirinchaos** [yandex-php/php-yandex-geo#6]
После смены адреса запросов у яндекса с http, на https перестала работать локальная версия. Есть способы заставить её работать?

**Comment by dmkuznetsov** [comment]
А что именно не работает? Можете ошибку предоставить? http://stackoverflow.com/questions/3757071/php-debugging-curl

**Comment by aspirinchaos** [comment]
curl_error(): 127 is not a valid cURL handle resource выбрасывается ошибка при вызове CurlException.
var_dump($curl) выдает resource(127, curl)

**Comment by dmkuznetsov** [comment]
Тут дело не в библиотеке, а в настройках окружения.
Вероятно, не включена поддержка ssl (можно посмотреть в phpinfo() ), либо в консоли:

```bash

echo '<?php phpinfo(); ?>' | php 2>&1 |grep -i ssl
```

Чтобы правильно отдебажить запрос, нужно добавить строку в файл source/Yandex/Geo/Api.php

```php

 59     public function load()
 60     {
 61         $apiUrl = sprintf('https://geocode-maps.yandex.ru/%s/?%s', $this->_version, http_build_query($this->_filters));
 62         $curl = curl_init($apiUrl);
 63         curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
 64         curl_setopt($curl, CURLOPT_HTTPGET, 1);
 65         curl_setopt($curl, CURLOPT_VERBOSE, true);  // <-- добавить такую строку
```

Это будет выводить всю отладочную информацию о запросе на экран/консоль.
Пришлите debug-вывод и посмотрим, чего не хватает для корректной работы.

**Comment by MrZLO** [comment]
Здравствуйте, извиняюсь что не ответил сразу, я уже не занимаюсь тем проектом и нет доступа к файлам поэтому прислать нечего...13.08.2015, 19:25, "Dmitry Kuznetsov" <notifications@github.com>:Тут дело не в библиотеке, а в настройках окружения.
Вероятно, не включена поддержка ssl (можно посмотреть в phpinfo() ), либо в консоли:


echo '<?php phpinfo(); ?>' | php 2>&1 |grep -i ssl

Чтобы правильно отдебажить запрос, нужно добавить строку в файл source/Yandex/Geo/Api.php


 59     public function load()
 60     {
 61         $apiUrl = sprintf('https://geocode-maps.yandex.ru/%s/?%s', $this->_version, http_build_query($this->_filters));
 62         $curl = curl_init($apiUrl);
 63         curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
 64         curl_setopt($curl, CURLOPT_HTTPGET, 1);
 65         curl_setopt($curl, CURLOPT_VERBOSE, true);  // <-- добавить такую строку

Это будет выводить всю отладочную информацию о запросе на экран/консоль.
Пришлите debug-вывод и посмотрим, чего не хватает для корректной работы.

—Reply to this email directly or view it on GitHub.


  
  



-- Режим работы: режим.
