### ISSUE TITLE
Предложение.

### ISSUE THREAD

**Issue by Nik-ADA** [yandex-php/php-yandex-geo#9]
Столкнулся с тем что в ответ не попадает важное поле (ну по крайне мере для меня)
поле называется **kind** 

Думаю что будет полезно его иметь в ответе.

**Comment by dmkuznetsov** [comment]
Можете прислать pull-request?

**Comment by Nik-ADA** [comment]
Я решил следующим оброзом
между
https://github.com/yandex-php/php-yandex-geo/blob/master/source/Yandex/Geo/GeoObject.php#L19-L20

добавил следующее значение
`$data['kind'] = $rawData['metaDataProperty']['GeocoderMetaData']['kind'];`

**Comment by dmkuznetsov** [comment]
https://github.com/yandex-php/php-yandex-geo/commit/fe1da3b9fb40a6c9bbb1302de09a0675df8051e4
